### ISSUE TITLE
Missing imported modules

### ISSUE THREAD

**Issue by yongtang** [tensorflow/io#489]
See #487 for more details. At the moment some of the modules in tensorflow-io are missing when importing:

- bigquery
```
from tensorflow_io.bigquery.python.ops.bigquery_api import BigQueryClient
ModuleNotFoundError: No module named 'tensorflow_io.bigquery.python.ops.bigquery_api'
```
- cloud
```
  File "/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/cloud/__init__.py", line 22, in <module>
    from tensorflow_io.cloud.python.ops.bigquery_reader_ops import *
  File "/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/cloud/python/ops/bigquery_reader_ops.py", line 25, in <module>
    _bigquery_reader_so = _load_library("_bigquery_reader_ops.so")
  File "/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/__init__.py", line 59, in _load_library
    "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs))
NotImplementedError: unable to open file: _bigquery_reader_ops.so, from paths: ['/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/cloud/python/ops/_bigquery_reader_ops.so']
caused by: ['/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/cloud/python/ops/_bigquery_reader_ops.so: undefined symbol: _ZTVN10tensorflow10ReaderBaseE']
```
- dicom
```
  File "/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/dicom/__init__.py", line 26, in <module>
    from tensorflow_io.dicom.python.ops.dicom_ops import decode_dicom_data
  File "/usr/local/google/home/markdaoust/venv3/lib/python3.6/site-packages/tensorflow_io/dicom/python/ops/dicom_ops.py", line 25, in <module>
    decode_dicom_data = dicom_ops.decode_dicom_data
AttributeError: module '0bb84602ad9137f5e6d7401094b24438' has no attribute 'decode_dicom_data'
```

We will need to fix those bugs. Thanks @MarkDaoust for providing the information!

**Comment by Kat-ML** [comment]
Have you already fixed those bugs?

**Comment by yongtang** [comment]
@Kat-ML I have not been able to reproduce the issue on my local machine. If you could provide a configuration (Linux distribution type, version, tensorflow version, and tensorflow-io version/install) then I could take a further look.

**Comment by vlasenkoalexey** [comment]
Regarding bigquery, I believe issue exists in tensorflow-io 0.7.0 and fixed by https://github.com/tensorflow/io/pull/467

**Comment by MarkDaoust** [comment]
I'm still having a little trouble getting the api reference docs onto tensorflow.org.

I retried this with `!pip install tensorflow_io=0.9`, in a fresh virtual env with `pip install tensorflow==2.0`. Ubuntu 14.04.5 LTS. Python 3.7.

These are the errors I get now:

https://gist.github.com/MarkDaoust/8a399024b1b162fc61086119e3ddd947

Using this "recursive_import" function:

https://gist.github.com/MarkDaoust/c924f63247cb90e3b8f6879f65835ccb

While trying to python import all the submodules during [build_docs.py](https://github.com/tensorflow/io/blob/master/tools/docs/build_docs.py)

I can filter out all the errors using that version of "recursive_import" but anything that fails to import will just not get pushed to the site. 

Am I importing the wrong things (everything)? How is a user supposed to know which packages they should be importing? We could instead add explicit imports to the build_docs script, but that's adds maintenance that we'll likely forget to do.

Any suggestions?

**Comment by yongtang** [comment]
Thanks @MarkDaoust. Are you using dead snake's python 3.7 module (https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) with Ubuntu 14.04?

Let me take a look and see if I could fix the issue.

**Comment by yongtang** [comment]
@MarkDaoust Looks like dead snake's python 3.7 version does not work with Ubuntu 14.04 due to the SSL version. Do you have a docker image with Ubuntu 14.04 + Python 3.7 you are using so that I can give it a try?

**Comment by vlasenkoalexey** [comment]
Could you also check which pip version do you have (pip --version)?
By default Ubuntu installs 9.xx which, which is very old. If you run pip install tensorflow-io on pip 9.x it will only install tensorflow-io 0.7.x. In order to install 0.9.x you need to upgrade pip to latest version (19.x).

**Comment by MarkDaoust** [comment]
Okay here is something reproducible (Ubuntu 18.04.3 LTS, python 3.6.8, pip-19.3.1):
(Remove the `grep` below to get more detail for each error.)

```
docker pull tensorflow/tensorflow:latest-devel-py3
docker run --rm -it tensorflow/tensorflow:latest-py3 bash
pip install --upgrade pip
pip install tensorflow_io
curl -O https://raw.githubusercontent.com/tensorflow/docs/master/tools/tensorflow_docs/api_generator/utils.py
python -c "import tensorflow_io as tfio; import utils; utils.recursive_import(tfio)"  2>&1 | grep ERROR
```
```
ERROR:root:Failed to load module: 'tensorflow_io.audio'
ERROR:root:Failed to load package: 'tensorflow_io.audio'
ERROR:root:Failed to load module: 'tensorflow_io.bigtable.python.ops._bigtable'
ERROR:root:Failed to load module: 'tensorflow_io.cloud'
ERROR:root:Failed to load package: 'tensorflow_io.cloud'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.ffmpeg_ops'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io_golang'
ERROR:root:Failed to load module: 'tensorflow_io.ffmpeg'
ERROR:root:Failed to load package: 'tensorflow_io.ffmpeg'
ERROR:root:Failed to load module: 'tensorflow_io.grpc.libendpoint_cc_grpc'
ERROR:root:Failed to load module: 'tensorflow_io.grpc.libendpoint_proto'
ERROR:root:Failed to load module: 'tensorflow_io.hadoop.python.ops._hadoop_ops'
ERROR:root:Failed to load module: 'tensorflow_io.kinesis.python.ops._kinesis_ops'
ERROR:root:Failed to load module: 'tensorflow_io.libsvm.python.ops._libsvm_ops'
ERROR:root:Failed to load module: 'tensorflow_io.oss.python.ops.ossfs_ops'
ERROR:root:Failed to load module: 'tensorflow_io.pcap.python.ops._pcap_ops'
ERROR:root:Failed to load module: 'tensorflow_io.video'
ERROR:root:Failed to load package: 'tensorflow_io.video'
```

**Comment by yongtang** [comment]
Thanks @MarkDaoust ! I am able to reproduce the issue.

There are several reasons causing the module load errors.

One issue was that **FFmpeg was not installed**. Because FFmpeg is LGPL license, we could not bundle FFmpeg into tensorflow-io. Instead, in runtime it is loaded dynamically.

If FFmpeg is installed, then several ERROR could be removed. Below is the output:
```
docker pull tensorflow/tensorflow:latest-devel-py3
docker run --rm -it tensorflow/tensorflow:latest-py3 bash
apt-get -y -qq update
apt-get -y -qq install ffmpeg
pip install --upgrade pip
pip install tensorflow_io
curl -O https://raw.githubusercontent.com/tensorflow/docs/master/tools/tensorflow_docs/api_generator/utils.py
python -c "import tensorflow_io as tfio; import utils; utils.recursive_import(tfio)"  2>&1 | grep ERROR
```


ERROR output (less number than without `apt install ffmpeg`):
```
ERROR:root:Failed to load module: 'tensorflow_io.audio'
ERROR:root:Failed to load package: 'tensorflow_io.audio'
ERROR:root:Failed to load module: 'tensorflow_io.bigtable.python.ops._bigtable'
ERROR:root:Failed to load module: 'tensorflow_io.cloud'
ERROR:root:Failed to load package: 'tensorflow_io.cloud'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io_golang'
ERROR:root:Failed to load module: 'tensorflow_io.grpc.libendpoint_cc_grpc'
ERROR:root:Failed to load module: 'tensorflow_io.grpc.libendpoint_proto'
ERROR:root:Failed to load module: 'tensorflow_io.hadoop.python.ops._hadoop_ops'
ERROR:root:Failed to load module: 'tensorflow_io.kinesis.python.ops._kinesis_ops'
ERROR:root:Failed to load module: 'tensorflow_io.libsvm.python.ops._libsvm_ops'
ERROR:root:Failed to load module: 'tensorflow_io.oss.python.ops.ossfs_ops'
ERROR:root:Failed to load module: 'tensorflow_io.pcap.python.ops._pcap_ops'
```

For the remaining errors, **the following (and similarly)**:
```
['/usr/local/lib/python3.6/dist-packages/tensorflow_io/cloud/python/ops/_bigquery_reader_ops.so: undefined symbol: _ZTVN10tensorflow10ReaderBaseE']
```
is a GCC flag issue. I will create a PR to fix this issue.

And the final remaining errors all looks like:
```
ImportError: dynamic module does not define module export function (PyInit__pcap_ops)
```

I am looking into it, will try my best to fix it soon.

**Comment by MarkDaoust** [comment]
It looks like you're working hard at fixing these!

One more question about FFMPEG. Depending on the machine I run on get this even with ffmpeg installed, does this ring any bells for anyone?:

```
NotImplementedError: ('could not find ffmpeg after search through ', {'libtensorflow_io_ffmpeg_2.8.so': ['libavformat-ffmpeg.so.56', 'libavcodec-ffmpeg.so.56', 'libavutil-ffmpeg.so.54', 'libswscale-ffmpeg.so.3'], 'libtensorflow_io_libav_9.20.so': ['libavformat.so.54', 'libavcodec.so.54', 'libavutil.so.52', 'libswscale.so.2'], 'libtensorflow_io_ffmpeg_3.4.so': ['libavformat.so.57', 'libavformat.so.57', 'libavutil.so.55', 'libswscale.so.4']})
```

**Comment by yongtang** [comment]
Thanks @MarkDaoust! Since FFmpeg's library API changes from time to time, we could only support a limited range of shared object libraries. In tensorflow-io we try to probe a set of dependency on Ubuntu 14.04, 16.04, and 18.04. That is why you see there are three sets of libavformat.so with different version extensions.

In short tensorflow-io only support FFmpeg on **Ubuntu 14.04**, **16.04**, and **18.04**.

Note Ubuntu 14.04 FFmpeg support will be deprecated fairly soon as 14.04 has been EOL early this year.

I also created several PRs to try to fix the remaining issues.  PR #585 and PR #586 have been merged and  PR #587 and #588 are pending. Once PR #587 and #588 are merged, the number of errors will only be reduced to two:
```
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io'
ERROR:root:Failed to load module: 'tensorflow_io.core.python.ops.libtensorflow_io_golang'
```

I am actively looking into the above two ERRORs, I kind of think there might be some python c binding header inclusion issue. Haven't had a concrete idea yet though.

Will try to get the remaining one fixed soon.

**Comment by kvignesh1420** [comment]
@yongtang any updates on this?
